### ISSUE TITLE
I found tow bugs

### ISSUE THREAD

**Issue by hurryboylqs** [tenpoku1000/UEFI_FreeType_MSVC#1]
thank you your porting the musl c lib for uefi
but i found tow bugs
1:in file __stdio_read.c line 32
    EFI_STATUS status = efi_file->Read(efi_file, &len, &buf);
shuld be:
  EFI_STATUS status = efi_file->Read(efi_file, &len, buf);

2:in file __stdio_write.c line 25
EFI_STATUS status = efi_file->Write(efi_file, &len, (void*)&buf);

shuld be 
EFI_STATUS status = efi_file->Write(efi_file, &len, (void*)buf);

**Comment by tenpoku1000** [comment]
Thanks for the information that looks good. Sorry I didn't save the environment when it was first developed, so I couldn't fix it immediately.
In my current Visual Stidio 2019, I get a local variable access violation inside FreeType, and I get the same error when I port FreeType 2.10.4.
The same error occurs when porting FreeType 2.10.4. If you can fix this, I'd like to check and fix it.

The following is the original text in Japanese.

良さそうな情報をありがとう。開発当初の環境を保存していなかったので、即座に修正できず申し訳ないです。
今の Visual Stidio 2019 の場合、FreeType 内部でローカル変数のアクセス違反になり、FreeType 2.10.4 を
移植しても同様のエラーになります。これを解決出来たら、確認して修正したいです。

**Comment by tenpoku1000** [comment]
I have fixed the bug you pointed out, updated to FreeType 2.10.4, and committed the code to be buildable with Visual Stidio 2019. Thank you for your cooperation.

The following is the original text in Japanese.

ご指摘のバグを修正しました。FreeType 2.10.4 に更新し、Visual Stidio 2019 でビルド可能にしたコードをコミットしました。ご協力感謝いたします。
